
/**************************************************************\
Edition (auto):
##  --/--/---- by generate_exception_header.py

File Name:
##  @file generated_exception_header.hpp

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in 'cmake/config/exceptions/'
##  Used for exception code & message definition
\**************************************************************/

#ifndef GENERATED_EXCEPTION_HEADER_H
    #define GENERATED_EXCEPTION_HEADER_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <iterator> // std::size
    #include <cstddef>  // std::size_t
    #include <cstdint>  // std::uint8_t

namespace utils::exception { // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum class Code: std::size_t {
    Undefined = 0,
    NoPlugins,
    NoLoadedCamera,
    Runtime,
    Parser,
    ppmFile,
    InvalidAction,
    VectorInvalidIndex,
    ExceptionCodeRestriction,
    Exit,
    NotSupportedFunction,
    ANSIMouseEvent,
    IdOverflow,
    UnknowId,
    SharedObject,
    CliInternal,
    CliHook,
    CliMiddleware,
    CliParser,
    CliExecution,
    CliUndefined,
    Dlopen,
    Dlsym,
    Dlclose,
    ArgumentsNumber,
    InvalidArgument,
    IgnoredArgument,
    OptionOverride,
    MissingOptionArgument,
    MissingOption,
    MissingArgument,
    MissingEnvVar,
    InvalidDirectory,
    InvalidFile,
    InvalidFileExtension,
    CODE_SENTINEL // sentinel used for verification
};

/* Corresponding exception message for each code */
constexpr inline const char *Message[] = {
    /* Undefined */ "An undefined error has occured",
    /* NoPlugins */ "Wasn't able to find any plugins",
    /* NoLoadedCamera */ "Wasn't able to load any camera",
    /* Runtime */ "Error during the runtime",
    /* Parser */ "Error during the parsing",
    /* ppmFile */ "Error during the ppm file writing/reading",
    /* InvalidAction */ "Can't execute this action",
    /* VectorInvalidIndex */ "Invalid index on a vector",
    /* ExceptionCodeRestriction */ "Error during the setup of an exception",
    /* Exit */ "Exit",
    /* NotSupportedFunction */ "This function is not supported by this class",
    /* ANSIMouseEvent */ "Error during the read of the mouse event",
    /* IdOverflow */ "Can't distribute an id, uint32_t limits are reach",
    /* UnknowId */ "Try to edit an unknow id",
    /* SharedObject */ "An object created with dynamic code that was free is still alive",
    /* CliInternal */ "Internal error from the cli",
    /* CliHook */ "Error during a hook call",
    /* CliMiddleware */ "Error during a middleware call",
    /* CliParser */ "Error during the parsing",
    /* CliExecution */ "Error during the command execution",
    /* CliUndefined */ "An undefined error has append",
    /* Dlopen */ "Failed to load a dynamic library",
    /* Dlsym */ "Failed to load a function from a dynamic library",
    /* Dlclose */ "Failed to release a loaded dynamic library",
    /* ArgumentsNumber */ "Invalid number of arguments given, use '-h' for more information",
    /* InvalidArgument */ "Can't interpret this argument",
    /* IgnoredArgument */ "This argument won't be used",
    /* OptionOverride */ "Duplicated option, this will override the precedent",
    /* MissingOptionArgument */ "The option require argument that where not given",
    /* MissingOption */ "An option is missing",
    /* MissingArgument */ "An argument is missing",
    /* MissingEnvVar */ "An environement variable is missing",
    /* InvalidDirectory */ "Invalid directory given",
    /* InvalidFile */ "Invalid file given",
    /* InvalidFileExtension */ "The file extension is different than expected",
};

/* Potential default info: nullptr same as "[None]" */
constexpr inline const char *Info[] = {
    /* Undefined */ nullptr,
    /* NoPlugins */ nullptr,
    /* NoLoadedCamera */ nullptr,
    /* Runtime */ nullptr,
    /* Parser */ nullptr,
    /* ppmFile */ nullptr,
    /* InvalidAction */ nullptr,
    /* VectorInvalidIndex */ "Can't retrieve the value, the VectorX dosen't have this index",
    /* ExceptionCodeRestriction */ "Restriction trigerred on a code & type combination",
    /* Exit */ "Exit",
    /* NotSupportedFunction */ nullptr,
    /* ANSIMouseEvent */ nullptr,
    /* IdOverflow */ nullptr,
    /* UnknowId */ nullptr,
    /* SharedObject */ nullptr,
    /* CliInternal */ nullptr,
    /* CliHook */ nullptr,
    /* CliMiddleware */ nullptr,
    /* CliParser */ nullptr,
    /* CliExecution */ nullptr,
    /* CliUndefined */ nullptr,
    /* Dlopen */ nullptr,
    /* Dlsym */ nullptr,
    /* Dlclose */ nullptr,
    /* ArgumentsNumber */ nullptr,
    /* InvalidArgument */ nullptr,
    /* IgnoredArgument */ nullptr,
    /* OptionOverride */ nullptr,
    /* MissingOptionArgument */ nullptr,
    /* MissingOption */ nullptr,
    /* MissingArgument */ nullptr,
    /* MissingEnvVar */ nullptr,
    /* InvalidDirectory */ nullptr,
    /* InvalidFile */ nullptr,
    /* InvalidFileExtension */ nullptr,
};

/* Potential restriction on exception code */
// 0b0000 = no restriction	(allow all)
// 0b0001 = None			(allow None)
// 0b0010 = Fatal			(allow Fatal)
// 0b0100 = Error			(allow Error)
// 0b1000 = Warning			(allow Warning)
constexpr inline const std::uint8_t Restriction[] = {
    /* Undefined */ 0b0000, // allow: All
    /* NoPlugins */ 0b1110, // allow: Fatal, Error, Warning
    /* NoLoadedCamera */ 0b1110, // allow: Fatal, Error, Warning
    /* Runtime */ 0b1110, // allow: Fatal, Error, Warning
    /* Parser */ 0b1110, // allow: Fatal, Error, Warning
    /* ppmFile */ 0b0110, // allow: Fatal, Error
    /* InvalidAction */ 0b1110, // allow: Fatal, Error, Warning
    /* VectorInvalidIndex */ 0b1110, // allow: Fatal, Error, Warning
    /* ExceptionCodeRestriction */ 0b0110, // allow: Fatal, Error
    /* Exit */ 0b0001, // allow: None
    /* NotSupportedFunction */ 0b0110, // allow: Fatal, Error
    /* ANSIMouseEvent */ 0b0110, // allow: Fatal, Error
    /* IdOverflow */ 0b0110, // allow: Fatal, Error
    /* UnknowId */ 0b0110, // allow: Fatal, Error
    /* SharedObject */ 0b1110, // allow: Fatal, Error, Warning
    /* CliInternal */ 0b0110, // allow: Fatal, Error
    /* CliHook */ 0b1110, // allow: Fatal, Error, Warning
    /* CliMiddleware */ 0b1110, // allow: Fatal, Error, Warning
    /* CliParser */ 0b0000, // allow: All
    /* CliExecution */ 0b0110, // allow: Fatal, Error
    /* CliUndefined */ 0b0110, // allow: Fatal, Error
    /* Dlopen */ 0b0110, // allow: Fatal, Error
    /* Dlsym */ 0b0110, // allow: Fatal, Error
    /* Dlclose */ 0b0110, // allow: Fatal, Error
    /* ArgumentsNumber */ 0b0110, // allow: Fatal, Error
    /* InvalidArgument */ 0b1110, // allow: Fatal, Error, Warning
    /* IgnoredArgument */ 0b1110, // allow: Fatal, Error, Warning
    /* OptionOverride */ 0b1001, // allow: None, Warning
    /* MissingOptionArgument */ 0b0110, // allow: Fatal, Error
    /* MissingOption */ 0b1110, // allow: Fatal, Error, Warning
    /* MissingArgument */ 0b1110, // allow: Fatal, Error, Warning
    /* MissingEnvVar */ 0b1110, // allow: Fatal, Error, Warning
    /* InvalidDirectory */ 0b1110, // allow: Fatal, Error, Warning
    /* InvalidFile */ 0b1110, // allow: Fatal, Error, Warning
    /* InvalidFileExtension */ 0b1110, // allow: Fatal, Error, Warning
};

// Check at the compile time the correspondece between the message & code
static_assert(std::size(Message) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");
static_assert(std::size(Info) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The info array doesn't correspond to the available exception codes");
static_assert(std::size(Restriction) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The restriction array doesn't correspond to the available exception codes");

} // namespace end
#endif /* GENERATED_EXCEPTION_HEADER_H */
